### ISSUE TITLE
Concurrent write to websocket connection

### ISSUE THREAD

**Issue by nanom1t** [hirokisan/bybit#104]
Hi,

I'm trying to close a websocket service, but I get a panic. I've also tried with mutex, but it didn't help. I've few goroutines connecting to websockets and I'm using wsService.Close() to close a connection.

Could you please check your code? How to properly close a connection?

```
	wsClient := bybit.NewWebsocketClient().WithAuth(config.Key, config.Secret)
	wsService, err := wsClient.V5().Private()
        err = wsService.Subscribe()
		if err != nil {
			return
		}
...
      err = wsService.Start(context.Background(), errHandler)
      if err != nil {
	      return
      }
```

```
panic: concurrent write to websocket connection

goroutine 70 [running]:
github.com/gorilla/websocket.(*messageWriter).flushFrame(0xc0004ae330, 0x1, {0x0?, 0x0?, 0x0?})
	/path/vendor/github.com/gorilla/websocket/conn.go:617 +0x50b
github.com/gorilla/websocket.(*messageWriter).Close(0xc0002870b0?)
	/path/vendor/github.com/gorilla/websocket/conn.go:731 +0x45
github.com/gorilla/websocket.(*Conn).beginMessage(0xc0003022c0, 0xc0002870b0, 0x8)
	/path/vendor/github.com/gorilla/websocket/conn.go:480 +0x42
github.com/gorilla/websocket.(*Conn).NextWriter(0xc0003022c0, 0x8)
	/path/vendor/github.com/gorilla/websocket/conn.go:520 +0x45
github.com/gorilla/websocket.(*Conn).WriteMessage(0x540eb0?, 0xc000072280?, {0xc00026aeb8, 0x2, 0x2})
	/path/vendor/github.com/gorilla/websocket/conn.go:773 +0x152
github.com/hirokisan/bybit/v2.(*V5WebsocketPrivateService).Close(0xc000286ed0)
	/path/vendor/github.com/hirokisan/bybit/v2/v5_ws_private.go:234 +0x59
github.com/hirokisan/bybit/v2.(*V5WebsocketPrivateService).Start(0xc000286ed0, {0x810e48, 0xc00001a730}, 0xc0004ce060)
	/path/vendor/github.com/hirokisan/bybit/v2/v5_ws_private.go:155 +0x377

```

Thanks

**Comment by hirokisan** [comment]
Thank you for raising the issue.

I have been busy for a while and will try to find time to investigate this issue.

**Comment by hirokisan** [comment]
@nanom1t 

https://github.com/hirokisan/bybit/issues/104#issuecomment-1480885116

Do you think this will solve the problem?

**Comment by hirokisan** [comment]
And I also corresponded to concurrency with this PR. 

https://github.com/hirokisan/bybit/pull/105

**Comment by nanom1t** [comment]
@hirokisan try to use `wsService.Close()` from other goroutine after some time delay to reproduce this bug. I need to properly close a websocket connection from other goroutine.

Here we started a goroutine which is listening a websocket and it works. But the websocket connection will be closed after program exits. I need to munually close a websocket connection, so I'm using wsService as global variable and call  `wsService.Close()` method to do this.
```
eg.Go(func() error {
	wsService, err := wsClient.V5().Private()
	if err = wsService.Subscribe(); err != nil {
		return fmt.Errorf("subscribe: %w", err)
	}
	if err := wsService.Start(context.Background(), nil); err != nil {
		return fmt.Errorf("start: %w", err)
	}
	return nil
})
```

**Comment by hirokisan** [comment]
>I think that PR105 - https://github.com/hirokisan/bybit/pull/105 should solve this issue, but will try to check.

I see. Please give it a try.

**Comment by nanom1t** [comment]
@hirokisan looks like it is working now without errors. Thanks
