### ISSUE TITLE
[bug] CancelOrder cannot find OrderLinkID

### ISSUE THREAD

**Issue by davidphay** [hirokisan/bybit#129]
Hello, I think there is an issue on `CancelOrder `function with `OrderLinkID`, when I try to cancel an order I have an error `110001, Order does not exist`:

This is the code to reproduce the bug:
```
package main

import (
	"github.com/hirokisan/bybit/v2"
	log "github.com/sirupsen/logrus"
)

func main() {
	client := bybit.NewClient().WithBaseURL("https://api-testnet.bybit.com").WithAuth("xxx", "xxx")

	symbol := bybit.SymbolV5("BTCUSDT")
	orderlinkid := "test_003"

       // create the order
	client.V5().Order().CreateOrder(bybit.V5CreateOrderParam{
		Category:    bybit.CategoryV5Linear,
		Symbol:      symbol,
		Side:        bybit.Side("Buy"),
		OrderType:   bybit.OrderTypeMarket,
		Qty:         "0.01",
		OrderLinkID: &orderlinkid,
	})

        // ensure the order has been created
	order, err := client.V5().Order().GetOpenOrders(bybit.V5GetOpenOrdersParam{
		Category:    bybit.CategoryV5Linear,
		Symbol:      &symbol,
		OrderLinkID: &orderlinkid,
	})

	if err != nil {
		log.Error(err)
	} else {
		log.Infof("Symbol: %s", order.Result.List[0].Symbol)
		log.Infof("OrderLinkID: %s", order.Result.List[0].OrderLinkID)
	}


       // Remove the order
	_, err = client.V5().Order().CancelOrder(bybit.V5CancelOrderParam{
		Category:    bybit.CategoryV5Linear,
		Symbol:      symbol,
		OrderLinkID: &orderlinkid,
	})

	if err != nil {
		log.Error(err)
	}
}
```

An this is the output:
```
INFO[0000] Symbol: BTCUSDT                              
INFO[0000] OrderLinkID: test_003                        
ERRO[0001] 110001, Order does not exist
```

Did I miss something wrong ?

**Comment by hirokisan** [comment]
@davidphay 

Since CreateOrder is executed in OrderTypeMarket, the Order is processed immediately, so the Order should not be cancelable.

You should be able to tell by checking the OrderStatus included in the GetOpenOrders Response.
https://github.com/hirokisan/bybit/blob/931bcfeb98ba93175e01eac38b8414f9abb85991/v5_order_service.go#L218

**Comment by davidphay** [comment]
> @davidphay
> 
> Since CreateOrder is executed in OrderTypeMarket, the Order is processed immediately, so the Order should not be cancelable.
> 
> You should be able to tell by checking the OrderStatus included in the GetOpenOrders Response.
> 
> https://github.com/hirokisan/bybit/blob/931bcfeb98ba93175e01eac38b8414f9abb85991/v5_order_service.go#L218

So how can we close a position with the API ?

Another weird things, I can't create an order with the same OrderLinkId after the previous position has been Filled or Cancelled.

I'm wondering if the issue is only on the testnet or not

**Comment by hirokisan** [comment]
>how can we close a position with the API ?

For example, it would be possible to eliminate the position by executing a Place Order.

>I can't create an order with the same OrderLinkId after the previous position has been Filled

(I think it's `previous order`, not `previous position`)

Since the orderLinkId you specified has already been assigned to an order, I don't think you can assign the same orderLinkId to another order.

**Comment by hirokisan** [comment]
It should be resolved and closed.
