### ISSUE TITLE
USDT Derivatives balance empty

### ISSUE THREAD

**Issue by Nitradamus** [hirokisan/bybit#14]
Hello,

Thanks for this module! I was trying to get the balance for my USDT derivatives wallet on bybit, but it seems I always get an empty response. Can you point me in the right direction?

```
package main

import (
	"fmt"

	"github.com/hirokisan/bybit"
)

func main() {

	client := bybit.NewClient().WithAuth("xxxxx", "xxxxxxx")
	res, err := client.Wallet().Balance(bybit.CoinUSDT)
	if err != nil {
		fmt.Println(err)
	}
	if client.HasAuth() {
		fmt.Println(res.Result)
	}
}
```

thanks in advance!

**Comment by hirokisan** [comment]
@Nitradamus 

Thanks for your comment.

Your API key may have expired, please check it on the admin page.

**Comment by hirokisan** [comment]
Otherwise, I think you can find other reason inside `CommonResponse` like below

```
fmt.Println(res.CommonResponse)
```

https://github.com/hirokisan/bybit/blob/b119d59acd07a0a00aedc4d01f8bbcf4aac25ead/service.go#L4-L13

**Comment by Nitradamus** [comment]
Ah, it seems my key expired just that day. Thanks a lot :)

I am trying to get my wallet balance and unrealised PNL from the result, but it seems I can't query it directly from the res.Result. Is there any way I can access these? like res.Equity, res.UnrealisedPnl

Thanks again :)

**Comment by hirokisan** [comment]
You can access these like below

```
res.Result.Balance[bybit.CoinUSDT].Equity
res.Result.Balance[bybit.CoinUSDT].UnrealisedPnl
```

**Comment by Nitradamus** [comment]
Thanks alot for the instructions, all is working fine now. Thanks again for this module!
