### ISSUE TITLE
Timestamp errors

### ISSUE THREAD

**Issue by rsm778877** [hirokisan/bybit#140]
Hi,

The exchange sometimes returns errors:
```
Error 10002, invalid request, please check your server timestamp or recv_window param. req_timestamp[1693378842140],server_timestamp[1693378847528],recv_window[5000]
```
How to fix this?

Thanks

**Comment by hirokisan** [comment]
@rsm778877 

Thank you for your comment.

@Sagleft has added a way to handle this, so please check it out.
https://github.com/hirokisan/bybit/pull/134

**Comment by nanom1t** [comment]
@hirokisan will it work automatically or should I set some params/options?

**Comment by hirokisan** [comment]
You should be able to synchronize time differences by calling SyncServerTime.

ref: https://github.com/hirokisan/bybit/blob/0298136702eb0d57542c47cf2732f52a921c12a4/client.go#L419-L430

**Comment by hirokisan** [comment]
I will close it once because time has passed.
