### ISSUE TITLE
Missing property in V5GetPositionInfoItem

### ISSUE THREAD

**Issue by id-petrov** [hirokisan/bybit#154]
Hello, looking at v5_position_service.go -> V5GetPositionInfoItem there seems to be missing properties : positionBalance and adlRankIndicator

Info: https://bybit-exchange.github.io/docs/v5/position#response-parameters

EDIT: there are actually two

**Comment by hirokisan** [comment]
@id-petrov 

Thank you very much for your support.

Just merged.
https://github.com/hirokisan/bybit/pull/155
