### ISSUE TITLE
Custom http client

### ISSUE THREAD

**Issue by oneart-dev** [hirokisan/bybit#17]
Hello, 
would be nice to have option for more customization.
Providing custom http client with custom transport will give option to use proxy.
Also when API limit reached custom client will prevent from making requests.

Sadly changing http client globally not an option as we do not make requests to other exchanges as well.

**Comment by oneart-dev** [comment]
forked it and fixed some issues. Also I know why LinearExecutionListResponse do not work, it should be GET request not POST. 

Error managing its quite a big problem. Responses do not checked for any http errors. It will produce marshal error instead. 

I have quite a few changes in code and probably will do quite a lot more in a few days. Feel free to use code from my fork (https://github.com/oneart-dev/bybit)

**Comment by hirokisan** [comment]
Thanks for your feedback!

I will try to reflect the points you raised.
