### ISSUE TITLE
Turnover in kline request is wrong

### ISSUE THREAD

**Issue by s-prosvirnin** [hirokisan/bybit#171]
https://github.com/hirokisan/bybit/blob/5f697f606fecc8475ff43c88c7b1a2969ad238a6/v5_market_service.go#L88

It is necessary to take the sixth index, not the fifth

**Comment by hirokisan** [comment]
@s-prosvirnin Thank you for pointing out the correction!

Fixed and released.
https://github.com/hirokisan/bybit/releases/tag/v2.30.3

**Comment by s-prosvirnin** [comment]
super!
