### ISSUE TITLE
Update types

### ISSUE THREAD

**Issue by apeman76** [hirokisan/bybit#175]
Hello,
Bybit has made some changes to its api and the type of risk limit requests and results have changed.
They now include a Cursor field, which is used to grab the next page of risk limits.
It seems like the library does not support these yet, and I cant use a normal map interface for the request
Could this be updated?

https://bybit-exchange.github.io/docs/changelog/v5#2024-05-09
https://bybit-exchange.github.io/docs/v5/market/risk-limit

Thank you

**Comment by hirokisan** [comment]
Thank you for raising the Issue!

It's going to take a while because I can't find time to work on it.

**Comment by hirokisan** [comment]
@apeman76 Just completed it. Check it out here.

https://github.com/hirokisan/bybit/releases/tag/v2.31.0
