### ISSUE TITLE
Add missing param curRealisedPnL for position list response

### ISSUE THREAD

**Issue by id-petrov** [hirokisan/bybit#190]
Hey,

there is a missing param, that is listed on the documentation found here: https://bybit-exchange.github.io/docs/v5/position#response-parameters

The param missing is "  curRealisedPnl | string | The realised PnL for the current holding position "

I have made a branch and fixed it, but can't commit to the repo duo to this error:

fatal: unable to access 'https://github.com/hirokisan/bybit.git/': The requested URL returned error: 403

Update: PR https://github.com/hirokisan/bybit/pull/191

**Comment by hirokisan** [comment]
Thank you for committing!

Released.

https://github.com/hirokisan/bybit/releases/tag/v2.34.4
