### ISSUE TITLE
Testnet

### ISSUE THREAD

**Issue by 0cv** [hirokisan/bybit#61]
Any reason to make this a constant? https://github.com/hirokisan/bybit/blob/main/client.go#L21

It would be good that it's configurable a way or another with the testnet (`https://api-testnet.bybit.com`). Also the main net has at least 2 endpoint: 
- `https://api.bybit.com`
- `https://api.bytick.com`

Maybe it's fine that it defaults to the main net. But it shall be possible to overwrite the endpoint

**Comment by hirokisan** [comment]
@0cv 

Thanks for your comment.

>Any reason to make this a constant?

Honestly, I don't have a strong commitment. It was just for simplicity.

As you say, it would be nice to have an option to switch endpoints.

I will try to modify it.

>with the testnet

A function is provided to generate a client for test like below.

https://github.com/hirokisan/bybit/blob/c7b19858bae7b3c991abe3defeeeb26bfa2a638a/testclient.go#L1-L50

**Comment by hirokisan** [comment]
>I will try to modify it

Just created PR https://github.com/hirokisan/bybit/pull/62 and merged it.

I'm going to close this issue.
